on:
  workflow_dispatch:

name: Clean pkgdown manually

jobs:
  pkgdown-gh-pages-manual:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::cli
            any::rcmdcheck
            any::pkgdown
            any::mapSpain
            any::classInt
            any::stars
            any::gganimate
            any::raster
            any::sp
            any::gstat
            any::scatterplot3d
            any::styler
            any::geofacet
            any::reactable
            any::leaflet
            any::tidyverse
            any::gifski
            any::geoR
            any::tidyterra
            ropenspain/rostemplate
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, clean = TRUE)'
