on:
  workflow_dispatch:

name: update-docs

jobs:
  update-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::rcmdcheck
            any::pkgdown
            any::mapSpain
            any::classInt
            any::raster
            any::stars
            any::gganimate
            any::sp
            any::gstat
            any::scatterplot3d
            any::styler
            any::geofacet
            any::reactable
            any::leaflet
            any::tidyverse
            any::gifski
            any::geoR
            dieghernan/pkgdev
            ropenspain/rostemplate

          needs: website

      - name: Update docs
        run: |

          pkgdev::update_docs()

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m 'Update docs with pkgdev' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - uses: r-lib/actions/check-r-package@v2

      - name: Deploy package
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = TRUE)'
